# Generated by Django 5.0.2 on 2024-03-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='age',
            field=models.IntegerField(),
        ),
    ]
